// generated by stringer -type=Dir; DO NOT EDIT

package dex

import "fmt"

const _Dir_name = "NoneDoubleUpSingleUpFortyFiveUpFlatFortyFiveDownSingleDownDoubleDownNotComputableRateOutOfRange"

var _Dir_index = [...]uint8{0, 4, 12, 20, 31, 35, 48, 58, 68, 81, 95}

func (i Dir) String() string {
	if i < 0 || i+1 >= Dir(len(_Dir_index)) {
		return fmt.Sprintf("Dir(%d)", i)
	}
	return _Dir_name[_Dir_index[i]:_Dir_index[i+1]]
}
